// Code generated by go generate; DO NOT EDIT.
// This file was generated from GraphQL schema

package model

type EnumEmailTemplateType string

const EnumEmailTemplateTypeRESET_PASSWORD EnumEmailTemplateType = "RESET_PASSWORD"
const EnumEmailTemplateTypePASSWORD_RESETED_NOTIFICATION EnumEmailTemplateType = "PASSWORD_RESETED_NOTIFICATION"
const EnumEmailTemplateTypeCHANGE_PASSWORD EnumEmailTemplateType = "CHANGE_PASSWORD"
const EnumEmailTemplateTypeWELCOME EnumEmailTemplateType = "WELCOME"
const EnumEmailTemplateTypeVERIFY_EMAIL EnumEmailTemplateType = "VERIFY_EMAIL"
const EnumEmailTemplateTypeCHANGE_EMAIL EnumEmailTemplateType = "CHANGE_EMAIL"

type EnumResourceType string

const EnumResourceTypeDATA EnumResourceType = "DATA"
const EnumResourceTypeAPI EnumResourceType = "API"
const EnumResourceTypeMENU EnumResourceType = "MENU"
const EnumResourceTypeUI EnumResourceType = "UI"
const EnumResourceTypeBUTTON EnumResourceType = "BUTTON"

type EnumSortByEnum string

const EnumSortByEnumCREATEDAT_DESC EnumSortByEnum = "CREATEDAT_DESC"
const EnumSortByEnumCREATEDAT_ASC EnumSortByEnum = "CREATEDAT_ASC"
const EnumSortByEnumUPDATEDAT_DESC EnumSortByEnum = "UPDATEDAT_DESC"
const EnumSortByEnumUPDATEDAT_ASC EnumSortByEnum = "UPDATEDAT_ASC"

type EnumUserStatus string

const EnumUserStatusSuspended EnumUserStatus = "Suspended"
const EnumUserStatusResigned EnumUserStatus = "Resigned"
const EnumUserStatusActivated EnumUserStatus = "Activated"
const EnumUserStatusArchived EnumUserStatus = "Archived"

type Enum__TypeKind string

const Enum__TypeKindSCALAR Enum__TypeKind = "SCALAR"
const Enum__TypeKindOBJECT Enum__TypeKind = "OBJECT"
const Enum__TypeKindINTERFACE Enum__TypeKind = "INTERFACE"
const Enum__TypeKindUNION Enum__TypeKind = "UNION"
const Enum__TypeKindENUM Enum__TypeKind = "ENUM"
const Enum__TypeKindINPUT_OBJECT Enum__TypeKind = "INPUT_OBJECT"
const Enum__TypeKindLIST Enum__TypeKind = "LIST"
const Enum__TypeKindNON_NULL Enum__TypeKind = "NON_NULL"

type EnumEmailScene string

const EnumEmailSceneRESET_PASSWORD EnumEmailScene = "RESET_PASSWORD"
const EnumEmailSceneVERIFY_EMAIL EnumEmailScene = "VERIFY_EMAIL"
const EnumEmailSceneCHANGE_EMAIL EnumEmailScene = "CHANGE_EMAIL"
const EnumEmailSceneMFA_VERIFY EnumEmailScene = "MFA_VERIFY"

type EnumOperator string

const EnumOperatorAND EnumOperator = "AND"
const EnumOperatorOR EnumOperator = "OR"

type EnumPolicyAssignmentTargetType string

const EnumPolicyAssignmentTargetTypeUSER EnumPolicyAssignmentTargetType = "USER"
const EnumPolicyAssignmentTargetTypeROLE EnumPolicyAssignmentTargetType = "ROLE"
const EnumPolicyAssignmentTargetTypeGROUP EnumPolicyAssignmentTargetType = "GROUP"
const EnumPolicyAssignmentTargetTypeORG EnumPolicyAssignmentTargetType = "ORG"
const EnumPolicyAssignmentTargetTypeAK_SK EnumPolicyAssignmentTargetType = "AK_SK"

type EnumPolicyEffect string

const EnumPolicyEffectALLOW EnumPolicyEffect = "ALLOW"
const EnumPolicyEffectDENY EnumPolicyEffect = "DENY"

type EnumUDFDataType string

const EnumUDFDataTypeSTRING EnumUDFDataType = "STRING"
const EnumUDFDataTypeNUMBER EnumUDFDataType = "NUMBER"
const EnumUDFDataTypeDATETIME EnumUDFDataType = "DATETIME"
const EnumUDFDataTypeBOOLEAN EnumUDFDataType = "BOOLEAN"
const EnumUDFDataTypeOBJECT EnumUDFDataType = "OBJECT"

type EnumUDFTargetType string

const EnumUDFTargetTypeNODE EnumUDFTargetType = "NODE"
const EnumUDFTargetTypeORG EnumUDFTargetType = "ORG"
const EnumUDFTargetTypeUSER EnumUDFTargetType = "USER"
const EnumUDFTargetTypeUSERPOOL EnumUDFTargetType = "USERPOOL"
const EnumUDFTargetTypeROLE EnumUDFTargetType = "ROLE"
const EnumUDFTargetTypePERMISSION EnumUDFTargetType = "PERMISSION"
const EnumUDFTargetTypeAPPLICATION EnumUDFTargetType = "APPLICATION"

type EnumWhitelistType string

const EnumWhitelistTypeUSERNAME EnumWhitelistType = "USERNAME"
const EnumWhitelistTypeEMAIL EnumWhitelistType = "EMAIL"
const EnumWhitelistTypePHONE EnumWhitelistType = "PHONE"

type Enum__DirectiveLocation string

const Enum__DirectiveLocationQUERY Enum__DirectiveLocation = "QUERY"
const Enum__DirectiveLocationMUTATION Enum__DirectiveLocation = "MUTATION"
const Enum__DirectiveLocationSUBSCRIPTION Enum__DirectiveLocation = "SUBSCRIPTION"
const Enum__DirectiveLocationFIELD Enum__DirectiveLocation = "FIELD"
const Enum__DirectiveLocationFRAGMENT_DEFINITION Enum__DirectiveLocation = "FRAGMENT_DEFINITION"
const Enum__DirectiveLocationFRAGMENT_SPREAD Enum__DirectiveLocation = "FRAGMENT_SPREAD"
const Enum__DirectiveLocationINLINE_FRAGMENT Enum__DirectiveLocation = "INLINE_FRAGMENT"
const Enum__DirectiveLocationVARIABLE_DEFINITION Enum__DirectiveLocation = "VARIABLE_DEFINITION"
const Enum__DirectiveLocationSCHEMA Enum__DirectiveLocation = "SCHEMA"
const Enum__DirectiveLocationSCALAR Enum__DirectiveLocation = "SCALAR"
const Enum__DirectiveLocationOBJECT Enum__DirectiveLocation = "OBJECT"
const Enum__DirectiveLocationFIELD_DEFINITION Enum__DirectiveLocation = "FIELD_DEFINITION"
const Enum__DirectiveLocationARGUMENT_DEFINITION Enum__DirectiveLocation = "ARGUMENT_DEFINITION"
const Enum__DirectiveLocationINTERFACE Enum__DirectiveLocation = "INTERFACE"
const Enum__DirectiveLocationUNION Enum__DirectiveLocation = "UNION"
const Enum__DirectiveLocationENUM Enum__DirectiveLocation = "ENUM"
const Enum__DirectiveLocationENUM_VALUE Enum__DirectiveLocation = "ENUM_VALUE"
const Enum__DirectiveLocationINPUT_OBJECT Enum__DirectiveLocation = "INPUT_OBJECT"
const Enum__DirectiveLocationINPUT_FIELD_DEFINITION Enum__DirectiveLocation = "INPUT_FIELD_DEFINITION"

type __Schema struct {
	Types            []__Type      `json:"types"`
	QueryType        __Type        `json:"queryType"`
	MutationType     *__Type       `json:"mutationType"`
	SubscriptionType *__Type       `json:"subscriptionType"`
	Directives       []__Directive `json:"directives"`
}

type __Type struct {
	Kind          Enum__TypeKind `json:"kind"`
	Name          *string        `json:"name"`
	Description   *string        `json:"description"`
	Fields        []__Field      `json:"fields"`
	Interfaces    []__Type       `json:"interfaces"`
	PossibleTypes []__Type       `json:"possibleTypes"`
	EnumValues    []__EnumValue  `json:"enumValues"`
	InputFields   []__InputValue `json:"inputFields"`
	OfType        *__Type        `json:"ofType"`
}

type __Field struct {
	Name              string         `json:"name"`
	Description       *string        `json:"description"`
	Args              []__InputValue `json:"args"`
	Type              __Type         `json:"type"`
	IsDeprecated      bool           `json:"isDeprecated"`
	DeprecationReason *string        `json:"deprecationReason"`
}

type __InputValue struct {
	Name         string  `json:"name"`
	Description  *string `json:"description"`
	Type         __Type  `json:"type"`
	DefaultValue *string `json:"defaultValue"`
}

type __EnumValue struct {
	Name              string  `json:"name"`
	Description       *string `json:"description"`
	IsDeprecated      bool    `json:"isDeprecated"`
	DeprecationReason *string `json:"deprecationReason"`
}

type __Directive struct {
	Name         string                    `json:"name"`
	Description  *string                   `json:"description"`
	Locations    []Enum__DirectiveLocation `json:"locations"`
	Args         []__InputValue            `json:"args"`
	IsRepeatable bool                      `json:"isRepeatable"`
}

type AccessTokenRes struct {
	AccessToken *string `json:"accessToken"`
	Exp         *int64  `json:"exp"`
	Iat         *int64  `json:"iat"`
}

type App2WxappLoginStrategy struct {
	TicketExpriresAfter              *int64 `json:"ticketExpriresAfter"`
	TicketExchangeUserInfoNeedSecret *bool  `json:"ticketExchangeUserInfoNeedSecret"`
}

type App2WxappLoginStrategyInput struct {
	TicketExpriresAfter              *int64 `json:"ticketExpriresAfter"`
	TicketExchangeUserInfoNeedSecret *bool  `json:"ticketExchangeUserInfoNeedSecret"`
}

type AuthorizedResource struct {
	Code    string            `json:"code"`
	Type    *EnumResourceType `json:"type"`
	Actions []string          `json:"actions"`
}

type AuthorizedTargetsActionsInput struct {
	Op   EnumOperator `json:"op"`
	List []*string    `json:"list"`
}

type AuthorizeResourceOpt struct {
	TargetType       EnumPolicyAssignmentTargetType `json:"targetType"`
	TargetIdentifier string                         `json:"targetIdentifier"`
	Actions          []string                       `json:"actions"`
}

type BatchOperationResult struct {
	SucceedCount int64    `json:"succeedCount"`
	FailedCount  int64    `json:"failedCount"`
	Message      *string  `json:"message"`
	Errors       []string `json:"errors"`
}

type ChangeEmailStrategy struct {
	VerifyOldEmail *bool `json:"verifyOldEmail"`
}

type ChangeEmailStrategyInput struct {
	VerifyOldEmail *bool `json:"verifyOldEmail"`
}

type ChangePhoneStrategy struct {
	VerifyOldPhone *bool `json:"verifyOldPhone"`
}

type ChangePhoneStrategyInput struct {
	VerifyOldPhone *bool `json:"verifyOldPhone"`
}

type CheckPasswordStrengthResult struct {
	Valid   bool    `json:"valid"`
	Message *string `json:"message"`
}

type CommonMessage struct {
	Message *string `json:"message"`
	Code    *int64  `json:"code"`
}

type ConfigEmailTemplateInput struct {
	Type       EnumEmailTemplateType `json:"type"`
	Name       string                `json:"name"`
	Subject    string                `json:"subject"`
	Sender     string                `json:"sender"`
	Content    string                `json:"content"`
	RedirectTo *string               `json:"redirectTo"`
	HasURL     *bool                 `json:"hasURL"`
	ExpiresIn  *int64                `json:"expiresIn"`
}

type CreateFunctionInput struct {
	Name        string  `json:"name"`
	SourceCode  string  `json:"sourceCode"`
	Description *string `json:"description"`
	Url         *string `json:"url"`
}

type CreateSocialConnectionInput struct {
	Provider    string                       `json:"provider"`
	Name        string                       `json:"name"`
	Logo        string                       `json:"logo"`
	Description *string                      `json:"description"`
	Fields      []SocialConnectionFieldInput `json:"fields"`
}

type CreateSocialConnectionInstanceFieldInput struct {
	Key   string `json:"key"`
	Value string `json:"value"`
}

type CreateSocialConnectionInstanceInput struct {
	Provider string                                      `json:"provider"`
	Fields   []*CreateSocialConnectionInstanceFieldInput `json:"fields"`
}

type CreateUserInput struct {
	Username          *string  `json:"username"`
	Email             *string  `json:"email"`
	EmailVerified     *bool    `json:"emailVerified"`
	Phone             *string  `json:"phone"`
	PhoneVerified     *bool    `json:"phoneVerified"`
	Unionid           *string  `json:"unionid"`
	Openid            *string  `json:"openid"`
	Nickname          *string  `json:"nickname"`
	Photo             *string  `json:"photo"`
	Password          *string  `json:"password"`
	RegisterSource    []string `json:"registerSource"`
	Browser           *string  `json:"browser"`
	Oauth             *string  `json:"oauth"`
	LoginsCount       *int64   `json:"loginsCount"`
	LastLogin         *string  `json:"lastLogin"`
	Company           *string  `json:"company"`
	LastIP            *string  `json:"lastIP"`
	SignedUp          *string  `json:"signedUp"`
	Blocked           *bool    `json:"blocked"`
	IsDeleted         *bool    `json:"isDeleted"`
	Device            *string  `json:"device"`
	Name              *string  `json:"name"`
	GivenName         *string  `json:"givenName"`
	FamilyName        *string  `json:"familyName"`
	MiddleName        *string  `json:"middleName"`
	Profile           *string  `json:"profile"`
	PreferredUsername *string  `json:"preferredUsername"`
	Website           *string  `json:"website"`
	Gender            *string  `json:"gender"`
	Birthdate         *string  `json:"birthdate"`
	Zoneinfo          *string  `json:"zoneinfo"`
	Locale            *string  `json:"locale"`
	Address           *string  `json:"address"`
	Formatted         *string  `json:"formatted"`
	StreetAddress     *string  `json:"streetAddress"`
	Locality          *string  `json:"locality"`
	Region            *string  `json:"region"`
	PostalCode        *string  `json:"postalCode"`
	Country           *string  `json:"country"`
	ExternalId        *string  `json:"externalId"`
}

type CustomSMSProvider struct {
	Enabled  *bool   `json:"enabled"`
	Provider *string `json:"provider"`
	Config   *string `json:"config"`
}

type CustomSMSProviderInput struct {
	Enabled  *bool   `json:"enabled"`
	Provider *string `json:"provider"`
	Config   *string `json:"config"`
}

type EmailTemplate struct {
	Type       EnumEmailTemplateType `json:"type"`
	Name       string                `json:"name"`
	Subject    string                `json:"subject"`
	Sender     string                `json:"sender"`
	Content    string                `json:"content"`
	RedirectTo *string               `json:"redirectTo"`
	HasURL     *bool                 `json:"hasURL"`
	ExpiresIn  *int64                `json:"expiresIn"`
	Enabled    *bool                 `json:"enabled"`
	IsSystem   *bool                 `json:"isSystem"`
}

type FrequentRegisterCheckConfig struct {
	TimeInterval *int64 `json:"timeInterval"`
	Limit        *int64 `json:"limit"`
	Enabled      *bool  `json:"enabled"`
}

type FrequentRegisterCheckConfigInput struct {
	TimeInterval *int64 `json:"timeInterval"`
	Limit        *int64 `json:"limit"`
	Enabled      *bool  `json:"enabled"`
}

type Function struct {
	Id          string  `json:"id"`
	Name        string  `json:"name"`
	SourceCode  string  `json:"sourceCode"`
	Description *string `json:"description"`
	Url         *string `json:"url"`
}

type Group struct {
	Code                string                        `json:"code"`
	Name                string                        `json:"name"`
	Description         *string                       `json:"description"`
	CreatedAt           *string                       `json:"createdAt"`
	UpdatedAt           *string                       `json:"updatedAt"`
	Users               PaginatedUsers                `json:"users"`
	AuthorizedResources *PaginatedAuthorizedResources `json:"authorizedResources"`
}

type Identity struct {
	Openid       *string `json:"openid"`
	UserIdInIdp  *string `json:"userIdInIdp"`
	UserId       *string `json:"userId"`
	ConnectionId *string `json:"connectionId"`
	IsSocial     *bool   `json:"isSocial"`
	Provider     *string `json:"provider"`
	UserPoolId   *string `json:"userPoolId"`
	RefreshToken *string `json:"refreshToken"`
	AccessToken  *string `json:"accessToken"`
}

type JWTTokenStatus struct {
	Code    *int64                `json:"code"`
	Message *string               `json:"message"`
	Status  *bool                 `json:"status"`
	Exp     *int64                `json:"exp"`
	Iat     *int64                `json:"iat"`
	Data    *JWTTokenStatusDetail `json:"data"`
}

type JWTTokenStatusDetail struct {
	Id         *string `json:"id"`
	UserPoolId *string `json:"userPoolId"`
	Arn        *string `json:"arn"`
}

type KeyValuePair struct {
	Key   string `json:"key"`
	Value string `json:"value"`
}

type LoginByEmailInput struct {
	Email        string  `json:"email"`
	Password     string  `json:"password"`
	CaptchaCode  *string `json:"captchaCode"`
	AutoRegister *bool   `json:"autoRegister"`
	ClientIp     *string `json:"clientIp"`
	Params       *string `json:"params"`
	Context      *string `json:"context"`
}

type LoginByPhoneCodeInput struct {
	Phone        string  `json:"phone"`
	Code         string  `json:"code"`
	AutoRegister *bool   `json:"autoRegister"`
	ClientIp     *string `json:"clientIp"`
	Params       *string `json:"params"`
	Context      *string `json:"context"`
}

type LoginByPhonePasswordInput struct {
	Phone        string  `json:"phone"`
	Password     string  `json:"password"`
	CaptchaCode  *string `json:"captchaCode"`
	AutoRegister *bool   `json:"autoRegister"`
	ClientIp     *string `json:"clientIp"`
	Params       *string `json:"params"`
	Context      *string `json:"context"`
}

type LoginByUsernameInput struct {
	Username     string  `json:"username"`
	Password     string  `json:"password"`
	CaptchaCode  *string `json:"captchaCode"`
	AutoRegister *bool   `json:"autoRegister"`
	ClientIp     *string `json:"clientIp"`
	Params       *string `json:"params"`
	Context      *string `json:"context"`
}

type LoginFailCheckConfig struct {
	TimeInterval *int64 `json:"timeInterval"`
	Limit        *int64 `json:"limit"`
	Enabled      *bool  `json:"enabled"`
}

type LoginFailCheckConfigInput struct {
	TimeInterval *int64 `json:"timeInterval"`
	Limit        *int64 `json:"limit"`
	Enabled      *bool  `json:"enabled"`
}

type LoginPasswordFailCheckConfig struct {
	TimeInterval *int64 `json:"timeInterval"`
	Limit        *int64 `json:"limit"`
	Enabled      *bool  `json:"enabled"`
}

type LoginPasswordFailCheckConfigInput struct {
	TimeInterval *int64 `json:"timeInterval"`
	Limit        *int64 `json:"limit"`
	Enabled      *bool  `json:"enabled"`
}

type Mfa struct {
	Id         string  `json:"id"`
	UserId     string  `json:"userId"`
	UserPoolId string  `json:"userPoolId"`
	Enable     bool    `json:"enable"`
	Secret     *string `json:"secret"`
}

type Node struct {
	Id                  string                        `json:"id"`
	OrgId               *string                       `json:"orgId"`
	Name                string                        `json:"name"`
	NameI18n            *string                       `json:"nameI18n"`
	Description         *string                       `json:"description"`
	DescriptionI18n     *string                       `json:"descriptionI18n"`
	Order               *int64                        `json:"order"`
	Code                *string                       `json:"code"`
	Root                *bool                         `json:"root"`
	Depth               *int64                        `json:"depth"`
	Path                []string                      `json:"path"`
	CodePath            []*string                     `json:"codePath"`
	NamePath            []string                      `json:"namePath"`
	CreatedAt           *string                       `json:"createdAt"`
	UpdatedAt           *string                       `json:"updatedAt"`
	Children            []string                      `json:"children"`
	Users               PaginatedUsers                `json:"users"`
	AuthorizedResources *PaginatedAuthorizedResources `json:"authorizedResources"`
}

type Org struct {
	Id       string `json:"id"`
	RootNode Node   `json:"rootNode"`
	Nodes    []Node `json:"nodes"`
}

type PaginatedAuthorizedResources struct {
	TotalCount int64                `json:"totalCount"`
	List       []AuthorizedResource `json:"list"`
}

type PaginatedAuthorizedTargets struct {
	List       []*ResourcePermissionAssignment `json:"list"`
	TotalCount *int64                          `json:"totalCount"`
}

type PaginatedDepartments struct {
	List       []UserDepartment `json:"list"`
	TotalCount int64            `json:"totalCount"`
}

type PaginatedFunctions struct {
	List       []Function `json:"list"`
	TotalCount int64      `json:"totalCount"`
}

type PaginatedGroups struct {
	TotalCount int64   `json:"totalCount"`
	List       []Group `json:"list"`
}

type PaginatedOrgs struct {
	TotalCount int64 `json:"totalCount"`
	List       []Org `json:"list"`
}

type PaginatedPolicies struct {
	TotalCount int64    `json:"totalCount"`
	List       []Policy `json:"list"`
}

type PaginatedPolicyAssignments struct {
	TotalCount int64              `json:"totalCount"`
	List       []PolicyAssignment `json:"list"`
}

type PaginatedRoles struct {
	TotalCount int64  `json:"totalCount"`
	List       []Role `json:"list"`
}

type PaginatedUserpool struct {
	TotalCount int64      `json:"totalCount"`
	List       []UserPool `json:"list"`
}

type PaginatedUsers struct {
	TotalCount int64  `json:"totalCount"`
	List       []User `json:"list"`
}

type Policy struct {
	Namespace        string             `json:"namespace"`
	Code             string             `json:"code"`
	IsDefault        bool               `json:"isDefault"`
	Description      *string            `json:"description"`
	Statements       []PolicyStatement  `json:"statements"`
	CreatedAt        *string            `json:"createdAt"`
	UpdatedAt        *string            `json:"updatedAt"`
	AssignmentsCount int64              `json:"assignmentsCount"`
	Assignments      []PolicyAssignment `json:"assignments"`
}

type PolicyAssignment struct {
	Code             string                         `json:"code"`
	TargetType       EnumPolicyAssignmentTargetType `json:"targetType"`
	TargetIdentifier string                         `json:"targetIdentifier"`
}

type PolicyStatement struct {
	Resource  string                     `json:"resource"`
	Actions   []string                   `json:"actions"`
	Effect    *EnumPolicyEffect          `json:"effect"`
	Condition []PolicyStatementCondition `json:"condition"`
}

type PolicyStatementCondition struct {
	Param    string `json:"param"`
	Operator string `json:"operator"`
	//Value    Object `json:"value"`
}

type PolicyStatementConditionInput struct {
	Param    string `json:"param"`
	Operator string `json:"operator"`
	//Value    Object `json:"value"`
}

type PolicyStatementInput struct {
	Resource  string                          `json:"resource"`
	Actions   []string                        `json:"actions"`
	Effect    *EnumPolicyEffect               `json:"effect"`
	Condition []PolicyStatementConditionInput `json:"condition"`
}

type QrcodeLoginStrategy struct {
	QrcodeExpiresAfter               *int64 `json:"qrcodeExpiresAfter"`
	ReturnFullUserInfo               *bool  `json:"returnFullUserInfo"`
	AllowExchangeUserInfoFromBrowser *bool  `json:"allowExchangeUserInfoFromBrowser"`
	TicketExpiresAfter               *int64 `json:"ticketExpiresAfter"`
}

type QrcodeLoginStrategyInput struct {
	QrcodeExpiresAfter               *int64 `json:"qrcodeExpiresAfter"`
	ReturnFullUserInfo               *bool  `json:"returnFullUserInfo"`
	AllowExchangeUserInfoFromBrowser *bool  `json:"allowExchangeUserInfoFromBrowser"`
	TicketExpiresAfter               *int64 `json:"ticketExpiresAfter"`
}

type RefreshAccessTokenRes struct {
	AccessToken *string `json:"accessToken"`
	Exp         *int64  `json:"exp"`
	Iat         *int64  `json:"iat"`
}

type RefreshToken struct {
	Token *string `json:"token"`
	Iat   *int64  `json:"iat"`
	Exp   *int64  `json:"exp"`
}

type RegisterByEmailInput struct {
	Email         string           `json:"email"`
	Password      string           `json:"password"`
	Profile       *RegisterProfile `json:"profile"`
	ForceLogin    *bool            `json:"forceLogin"`
	GenerateToken *bool            `json:"generateToken"`
	ClientIp      *string          `json:"clientIp"`
	Params        *string          `json:"params"`
	Context       *string          `json:"context"`
}

type RegisterByPhoneCodeInput struct {
	Phone         string           `json:"phone"`
	Code          string           `json:"code"`
	Password      *string          `json:"password"`
	Profile       *RegisterProfile `json:"profile"`
	ForceLogin    *bool            `json:"forceLogin"`
	GenerateToken *bool            `json:"generateToken"`
	ClientIp      *string          `json:"clientIp"`
	Params        *string          `json:"params"`
	Context       *string          `json:"context"`
}

type RegisterByUsernameInput struct {
	Username      string           `json:"username"`
	Password      string           `json:"password"`
	Profile       *RegisterProfile `json:"profile"`
	ForceLogin    *bool            `json:"forceLogin"`
	GenerateToken *bool            `json:"generateToken"`
	ClientIp      *string          `json:"clientIp"`
	Params        *string          `json:"params"`
	Context       *string          `json:"context"`
}

type RegisterProfile struct {
	Ip                *string        `json:"ip"`
	Oauth             *string        `json:"oauth"`
	Username          *string        `json:"username"`
	Nickname          *string        `json:"nickname"`
	Company           *string        `json:"company"`
	Photo             *string        `json:"photo"`
	Device            *string        `json:"device"`
	Browser           *string        `json:"browser"`
	Name              *string        `json:"name"`
	GivenName         *string        `json:"givenName"`
	FamilyName        *string        `json:"familyName"`
	MiddleName        *string        `json:"middleName"`
	Profile           *string        `json:"profile"`
	PreferredUsername *string        `json:"preferredUsername"`
	Website           *string        `json:"website"`
	Gender            *string        `json:"gender"`
	Birthdate         *string        `json:"birthdate"`
	Zoneinfo          *string        `json:"zoneinfo"`
	Locale            *string        `json:"locale"`
	Address           *string        `json:"address"`
	Formatted         *string        `json:"formatted"`
	StreetAddress     *string        `json:"streetAddress"`
	Locality          *string        `json:"locality"`
	Region            *string        `json:"region"`
	PostalCode        *string        `json:"postalCode"`
	Country           *string        `json:"country"`
	Udf               []UserDdfInput `json:"udf"`
}

type RegisterWhiteListConfig struct {
	PhoneEnabled    *bool `json:"phoneEnabled"`
	EmailEnabled    *bool `json:"emailEnabled"`
	UsernameEnabled *bool `json:"usernameEnabled"`
}

type RegisterWhiteListConfigInput struct {
	PhoneEnabled    *bool `json:"phoneEnabled"`
	EmailEnabled    *bool `json:"emailEnabled"`
	UsernameEnabled *bool `json:"usernameEnabled"`
}

type ResourcePermissionAssignment struct {
	TargetType       *EnumPolicyAssignmentTargetType `json:"targetType"`
	TargetIdentifier *string                         `json:"targetIdentifier"`
	Actions          []string                        `json:"actions"`
}

type Role struct {
	Id                  string                        `json:"id"`
	Namespace           string                        `json:"namespace"`
	Code                string                        `json:"code"`
	Arn                 string                        `json:"arn"`
	Description         *string                       `json:"description"`
	IsSystem            *bool                         `json:"isSystem"`
	CreatedAt           *string                       `json:"createdAt"`
	UpdatedAt           *string                       `json:"updatedAt"`
	Users               PaginatedUsers                `json:"users"`
	AuthorizedResources *PaginatedAuthorizedResources `json:"authorizedResources"`
	Parent              *Role                         `json:"parent"`
}

type SearchUserDepartmentOpt struct {
	DepartmentId               *string `json:"departmentId"`
	IncludeChildrenDepartments *bool   `json:"includeChildrenDepartments"`
}

type SearchUserGroupOpt struct {
	Code *string `json:"code"`
}

type SearchUserRoleOpt struct {
	Namespace *string `json:"namespace"`
	Code      string  `json:"code"`
}

type SetUdfValueBatchInput struct {
	TargetId string `json:"targetId"`
	Key      string `json:"key"`
	Value    string `json:"value"`
}

type SocialConnection struct {
	Provider    string                  `json:"provider"`
	Name        string                  `json:"name"`
	Logo        string                  `json:"logo"`
	Description *string                 `json:"description"`
	Fields      []SocialConnectionField `json:"fields"`
}

type SocialConnectionField struct {
	Key         *string                  `json:"key"`
	Label       *string                  `json:"label"`
	Type        *string                  `json:"type"`
	Placeholder *string                  `json:"placeholder"`
	Children    []*SocialConnectionField `json:"children"`
}

type SocialConnectionFieldInput struct {
	Key         *string                       `json:"key"`
	Label       *string                       `json:"label"`
	Type        *string                       `json:"type"`
	Placeholder *string                       `json:"placeholder"`
	Children    []*SocialConnectionFieldInput `json:"children"`
}

type SocialConnectionInstance struct {
	Provider string                           `json:"provider"`
	Enabled  bool                             `json:"enabled"`
	Fields   []*SocialConnectionInstanceField `json:"fields"`
}

type SocialConnectionInstanceField struct {
	Key   string `json:"key"`
	Value string `json:"value"`
}

type UpdateFunctionInput struct {
	Id          string  `json:"id"`
	Name        *string `json:"name"`
	SourceCode  *string `json:"sourceCode"`
	Description *string `json:"description"`
	Url         *string `json:"url"`
}

type UpdateUserInput struct {
	Email             *string `json:"email"`
	Unionid           *string `json:"unionid"`
	Openid            *string `json:"openid"`
	EmailVerified     *bool   `json:"emailVerified"`
	Phone             *string `json:"phone"`
	PhoneVerified     *bool   `json:"phoneVerified"`
	Username          *string `json:"username"`
	Nickname          *string `json:"nickname"`
	Password          *string `json:"password"`
	Photo             *string `json:"photo"`
	Company           *string `json:"company"`
	Browser           *string `json:"browser"`
	Device            *string `json:"device"`
	Oauth             *string `json:"oauth"`
	TokenExpiredAt    *string `json:"tokenExpiredAt"`
	LoginsCount       *int64  `json:"loginsCount"`
	LastLogin         *string `json:"lastLogin"`
	LastIP            *string `json:"lastIP"`
	Blocked           *bool   `json:"blocked"`
	Name              *string `json:"name"`
	GivenName         *string `json:"givenName"`
	FamilyName        *string `json:"familyName"`
	MiddleName        *string `json:"middleName"`
	Profile           *string `json:"profile"`
	PreferredUsername *string `json:"preferredUsername"`
	Website           *string `json:"website"`
	Gender            *string `json:"gender"`
	Birthdate         *string `json:"birthdate"`
	Zoneinfo          *string `json:"zoneinfo"`
	Locale            *string `json:"locale"`
	Address           *string `json:"address"`
	Formatted         *string `json:"formatted"`
	StreetAddress     *string `json:"streetAddress"`
	Locality          *string `json:"locality"`
	Region            *string `json:"region"`
	PostalCode        *string `json:"postalCode"`
	City              *string `json:"city"`
	Province          *string `json:"province"`
	Country           *string `json:"country"`
	ExternalId        *string `json:"externalId"`
}

type UpdateUserpoolInput struct {
	Name                      *string                            `json:"name"`
	Logo                      *string                            `json:"logo"`
	Domain                    *string                            `json:"domain"`
	Description               *string                            `json:"description"`
	UserpoolTypes             []string                           `json:"userpoolTypes"`
	EmailVerifiedDefault      *bool                              `json:"emailVerifiedDefault"`
	SendWelcomeEmail          *bool                              `json:"sendWelcomeEmail"`
	RegisterDisabled          *bool                              `json:"registerDisabled"`
	AppSsoEnabled             *bool                              `json:"appSsoEnabled"`
	AllowedOrigins            *string                            `json:"allowedOrigins"`
	TokenExpiresAfter         *int64                             `json:"tokenExpiresAfter"`
	FrequentRegisterCheck     *FrequentRegisterCheckConfigInput  `json:"frequentRegisterCheck"`
	LoginFailCheck            *LoginFailCheckConfigInput         `json:"loginFailCheck"`
	LoginFailStrategy         *string                            `json:"loginFailStrategy"`
	LoginPasswordFailCheck    *LoginPasswordFailCheckConfigInput `json:"loginPasswordFailCheck"`
	ChangePhoneStrategy       *ChangePhoneStrategyInput          `json:"changePhoneStrategy"`
	ChangeEmailStrategy       *ChangeEmailStrategyInput          `json:"changeEmailStrategy"`
	QrcodeLoginStrategy       *QrcodeLoginStrategyInput          `json:"qrcodeLoginStrategy"`
	App2WxappLoginStrategy    *App2WxappLoginStrategyInput       `json:"app2WxappLoginStrategy"`
	Whitelist                 *RegisterWhiteListConfigInput      `json:"whitelist"`
	CustomSMSProvider         *CustomSMSProviderInput            `json:"customSMSProvider"`
	LoginRequireEmailVerified *bool                              `json:"loginRequireEmailVerified"`
	VerifyCodeLength          *int64                             `json:"verifyCodeLength"`
}

type User struct {
	Id                  string                        `json:"id"`
	Arn                 string                        `json:"arn"`
	Status              *EnumUserStatus               `json:"status"`
	UserPoolId          string                        `json:"userPoolId"`
	Username            *string                       `json:"username"`
	Email               *string                       `json:"email"`
	EmailVerified       *bool                         `json:"emailVerified"`
	Phone               *string                       `json:"phone"`
	PhoneVerified       *bool                         `json:"phoneVerified"`
	Unionid             *string                       `json:"unionid"`
	Openid              *string                       `json:"openid"`
	Identities          []*Identity                   `json:"identities"`
	Nickname            *string                       `json:"nickname"`
	RegisterSource      []string                      `json:"registerSource"`
	Photo               *string                       `json:"photo"`
	Password            *string                       `json:"password"`
	Oauth               *string                       `json:"oauth"`
	Token               *string                       `json:"token"`
	TokenExpiredAt      *string                       `json:"tokenExpiredAt"`
	LoginsCount         *int64                        `json:"loginsCount"`
	LastLogin           *string                       `json:"lastLogin"`
	LastIP              *string                       `json:"lastIP"`
	SignedUp            *string                       `json:"signedUp"`
	Blocked             *bool                         `json:"blocked"`
	IsDeleted           *bool                         `json:"isDeleted"`
	Device              *string                       `json:"device"`
	Browser             *string                       `json:"browser"`
	Company             *string                       `json:"company"`
	Name                *string                       `json:"name"`
	GivenName           *string                       `json:"givenName"`
	FamilyName          *string                       `json:"familyName"`
	MiddleName          *string                       `json:"middleName"`
	Profile             *string                       `json:"profile"`
	PreferredUsername   *string                       `json:"preferredUsername"`
	Website             *string                       `json:"website"`
	Gender              *string                       `json:"gender"`
	Birthdate           *string                       `json:"birthdate"`
	Zoneinfo            *string                       `json:"zoneinfo"`
	Locale              *string                       `json:"locale"`
	Address             *string                       `json:"address"`
	Formatted           *string                       `json:"formatted"`
	StreetAddress       *string                       `json:"streetAddress"`
	Locality            *string                       `json:"locality"`
	Region              *string                       `json:"region"`
	PostalCode          *string                       `json:"postalCode"`
	City                *string                       `json:"city"`
	Province            *string                       `json:"province"`
	Country             *string                       `json:"country"`
	CreatedAt           *string                       `json:"createdAt"`
	UpdatedAt           *string                       `json:"updatedAt"`
	Roles               *PaginatedRoles               `json:"roles"`
	Groups              *PaginatedGroups              `json:"groups"`
	Departments         *PaginatedDepartments         `json:"departments"`
	AuthorizedResources *PaginatedAuthorizedResources `json:"authorizedResources"`
	ExternalId          *string                       `json:"externalId"`
	CustomData          []*UserCustomData             `json:"customData"`
}

type UserCustomData struct {
	Key      string          `json:"key"`
	Value    *string         `json:"value"`
	Label    *string         `json:"label"`
	DataType EnumUDFDataType `json:"dataType"`
}

type UserDdfInput struct {
	Key   string `json:"key"`
	Value string `json:"value"`
}

type UserDefinedData struct {
	Key      string          `json:"key"`
	DataType EnumUDFDataType `json:"dataType"`
	Value    string          `json:"value"`
	Label    *string         `json:"label"`
}

type UserDefinedDataInput struct {
	Key   string  `json:"key"`
	Value *string `json:"value"`
}

type UserDefinedDataMap struct {
	TargetId string            `json:"targetId"`
	Data     []UserDefinedData `json:"data"`
}

type UserDefinedField struct {
	TargetType EnumUDFTargetType `json:"targetType"`
	DataType   EnumUDFDataType   `json:"dataType"`
	Key        string            `json:"key"`
	Label      *string           `json:"label"`
	Options    *string           `json:"options"`
}

type UserDepartment struct {
	Department       Node    `json:"department"`
	IsMainDepartment bool    `json:"isMainDepartment"`
	JoinedAt         *string `json:"joinedAt"`
}

type UserPool struct {
	Id                               string                        `json:"id"`
	Name                             string                        `json:"name"`
	Domain                           string                        `json:"domain"`
	Description                      *string                       `json:"description"`
	Secret                           string                        `json:"secret"`
	JwtSecret                        string                        `json:"jwtSecret"`
	OwnerId                          *string                       `json:"ownerId"`
	UserpoolTypes                    []UserPoolType                `json:"userpoolTypes"`
	Logo                             string                        `json:"logo"`
	CreatedAt                        *string                       `json:"createdAt"`
	UpdatedAt                        *string                       `json:"updatedAt"`
	EmailVerifiedDefault             bool                          `json:"emailVerifiedDefault"`
	SendWelcomeEmail                 bool                          `json:"sendWelcomeEmail"`
	RegisterDisabled                 bool                          `json:"registerDisabled"`
	AppSsoEnabled                    bool                          `json:"appSsoEnabled"`
	ShowWxQRCodeWhenRegisterDisabled *bool                         `json:"showWxQRCodeWhenRegisterDisabled"`
	AllowedOrigins                   *string                       `json:"allowedOrigins"`
	TokenExpiresAfter                *int64                        `json:"tokenExpiresAfter"`
	IsDeleted                        *bool                         `json:"isDeleted"`
	FrequentRegisterCheck            *FrequentRegisterCheckConfig  `json:"frequentRegisterCheck"`
	LoginFailCheck                   *LoginFailCheckConfig         `json:"loginFailCheck"`
	LoginPasswordFailCheck           *LoginPasswordFailCheckConfig `json:"loginPasswordFailCheck"`
	LoginFailStrategy                *string                       `json:"loginFailStrategy"`
	ChangePhoneStrategy              *ChangePhoneStrategy          `json:"changePhoneStrategy"`
	ChangeEmailStrategy              *ChangeEmailStrategy          `json:"changeEmailStrategy"`
	QrcodeLoginStrategy              *QrcodeLoginStrategy          `json:"qrcodeLoginStrategy"`
	App2WxappLoginStrategy           *App2WxappLoginStrategy       `json:"app2WxappLoginStrategy"`
	Whitelist                        *RegisterWhiteListConfig      `json:"whitelist"`
	CustomSMSProvider                *CustomSMSProvider            `json:"customSMSProvider"`
	PackageType                      *int64                        `json:"packageType"`
	UseCustomUserStore               *bool                         `json:"useCustomUserStore"`
	LoginRequireEmailVerified        *bool                         `json:"loginRequireEmailVerified"`
	VerifyCodeLength                 *int64                        `json:"verifyCodeLength"`
}

type UserPoolType struct {
	Code        *string   `json:"code"`
	Name        *string   `json:"name"`
	Description *string   `json:"description"`
	Image       *string   `json:"image"`
	Sdks        []*string `json:"sdks"`
}

type WhiteList struct {
	CreatedAt *string `json:"createdAt"`
	UpdatedAt *string `json:"updatedAt"`
	Value     string  `json:"value"`
}
